name: Create File and Push Workflow

on:
  workflow_dispatch:
    inputs:
      nome:
        description: 'Nome'
        required: true
      sobrenome:
        description: 'Sobrenome'
        required: true
      idade:
        description: 'Idade'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NOME: ${{ github.event.inputs.nome }}
      SOBRENOME: ${{ github.event.inputs.sobrenome }}
      IDADE: ${{ github.event.inputs.idade }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create file with inputs
        run: |
          python template_jinja2.py

      - name: Create and push branch dev
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b dev
          git add .
          git commit -m "Adicionado arquivo com dados"
          git push origin dev
