name: Create File and Push Workflow

on:
  workflow_dispatch:
    inputs:
      nome:
        description: 'Nome'
        required: true
      sobrenome:
        description: 'Sobrenome'
        required: true
      idade:
        description: 'Idade'
        required: true

run-name: ${{ github.event.inputs.nome }}

env:
  NOME: ${{ github.event.inputs.nome }}
  SOBRENOME: ${{ github.event.inputs.sobrenome }}
  IDADE: ${{ github.event.inputs.idade }}
  GITHUB_SHA: 3e932126ff38cf897c1a3ffc554270192baa39dd
  GITHUB_WORKFLOW_SHA: 3e932126ff38cf897c1a3ffc554270192baa39dd
  GITHUB_ACTOR_ID: 1312313212312



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create String Artifact
        run: echo ${{ github }}
    
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ github.event.inputs.nome }}
      #     path: artifact.txt
    
      # - name: Checkout repository
      #   uses: actions/checkout@v2
      
      # - name: Create file with inputs
      #   run: |
      #     env
      #     python template_jinja2.py
      #     sleep 1m

      # - name: Create and push branch dev
      #   run: |
      #     git config --global user.email "actions@github.com"
      #     git config --global user.name "GitHub Actions"
      #     git checkout -b dev
      #     git add .
      #     git commit -m "Adicionado arquivo com dados"
      #     git push origin dev

  
